image: alpine

pages:
  tags:
  - docker
  - tiny 
  script:
  - apk update && apk add doxygen graphviz ttf-freefont texlive-full
  - cd docs && doxygen Doxyfile
  - mv docs/doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
