image: ubuntu:latest

pages:
  tags:
  - docker
  - tiny 
  script:
  - apt update
  - apt install -y graphviz fonts-freefont-ttf ghostscript texlive doxygen
  - cd docs && doxygen Doxyfile
  - mv docs/doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

