image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/hicr/docs

pages:
  tags:
  - docker
  - tiny 
  script:
  - cd docs && ./build.sh && cd .. 
  - mv docs/doxygen/html public
  artifacts:
    paths:
    - public
  only:
  - master
