build:
  image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/hicr/buildenv-x86_64:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
  - docker
  - high-core 
  - x86
  - infiniband
  script:
  - export HOME=/home/hicr
  - source /home/hicr/.hicr-env.sh
  - echo "Building..."
  - mkdir build
  - meson setup build -Dbuildtype=debug -Db_coverage=true -Dbackends=hwloc,pthreads,mpi,lpf,nosv,boost,opencl -Dfrontends=channel,RPCEngine,tasking,objectStore -DbuildTests=true -DbuildExamples=true -DcompileWarningsAsErrors=true
  - meson compile -C build
  - echo "Running tests..."
  - meson test -C build
  - echo "Creating coverage report..."
  - ninja -C build coverage
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    when: always
    paths:
      - build/meson-logs/*
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/meson-logs/coverage.xml 
  only:
  - master

build-ascend:
  image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/hicr/buildenv-ascend-arm64v8:latest
  tags:
  - docker
  - ascend
  script:
  - source /home/hicr/.hicr-env.sh
  - echo "$PATH"
  - echo "Building..."
  - mkdir build
  - meson setup build -Dbackends=hwloc,pthreads,ascend,boost -Dfrontends= -DbuildTests=true -DbuildExamples=true -DcompileWarningsAsErrors=true
  - meson compile -C build
  - echo "Running tests..."
  - meson test -C build
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    when: always
    paths:
      - build/meson-logs/*
  only:
  - master