image: alpine:3.18.3

pages:
  tags:
  - docker
  - tiny 
  before_script:
  - apk update && apk add doxygen graphviz ttf-freefont ghostscript texlive 
  script:
  - cd docs && doxygen Doxyfile
  - mv docs/doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
