image: alpine

pages:
  tags:
  - docker
  - tiny 
  script:
  - apk update && apk add doxygen graphviz ttf-freefont texlive texmf-dist-latexextra texlive-dvi
  - cd docs && doxygen Doxyfile
  - mkdir .public
  - cp -r doxygen/html/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
