image: alpine:3.18.3

pages:
  tags:
  - docker
  - tiny 
  script:
  - apk update && apk add doxygen graphviz ttf-freefont ghostscript texlive && cd docs && doxygen Doxyfile && mv docs/doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
