image: alpine

pages:
  tags:
  - docker
  - tiny 
  script:
  - apk update && apk add doxygen graphviz ttf-freefont texlive texmf-dist-latexextra texlive-dvi
  - cd docs && doxygen Doxyfile
  - mv doxygen/html public
  artifacts:
    paths:
    - public
  only:
  - master
