docs:
  image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/hicr/docs:latest
  tags:
  - docker
  - tiny 
  script:
  - echo "Checking HiCR source and test formatting..."
  - .build-tools/style/check-style.sh check include
  - .build-tools/style/check-style.sh check tests
  - echo "Building code documentation..."
  - make -j1 -C docs
  only: 
  - master
  - develop
  - merge_requests
  - tags

pages:
  image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/hicr/docs:latest
  tags:
  - docker
  - tiny 
  script:
  - echo "Building code documentation..."
  - make -j1 -C docs
  - mv docs/build/html public
  artifacts:
    paths:
    - public
  only:
  - master
  
build:
  image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/hicr/buildenv:latest
  tags:
  - docker
  - high-core 
  - x86
  script:
  - echo "Building..."
  - mkdir build
  - meson setup build -Db_coverage=true -Dbackends=sharedMemory -DbuildTests=true -DbuildExamples=true 
  - meson compile -C build
  - echo "Running tests..."
  - meson test -C build
  - echo "Creating coverage report..."
  - ninja -C build coverage
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    when: always
    paths:
      - build/meson-logs/*
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/meson-logs/coverage.xml 
  only:
  - master
  - develop 
  - merge_requests
  - tags

