image: python:3.6-alpine

pages:
  tags:
  - docker
  - tiny 
  script:
  - apk update && apk add doxygen graphviz ttf-freefont texlive texmf-dist-latexextra texlive-dvi texlive-font-utils
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinxcontrib-bibtex
  - pip install doxysphinx
  - cd docs && ./build.sh && cd ..
  - mv docs/doxygen/html public
  artifacts:
    paths:
    - public
  only:
  - master
