docs:
  image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/hicr/docs:latest
  tags:
  - docker
  - tiny 
  script:
  - echo "Obtaining build tools..."
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/build.git .build --recurse-submodules
  - echo "Checking style..."
  - cp .build/style/clang-format .clang-format
  - .build/style/check-style.sh check include
  - .build/style/check-style.sh check tests
  - echo "Checking code documentation..."
  - make -C docs
  only:
  - master
  - merge_requests

build:
  image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/hicr/buildenv:latest
  tags:
  - docker
  - high-core 
  - x86
  script:
  - echo "Building..."
  - mkdir build
  - meson setup build -Db_coverage=true
  - meson compile -C build
  - echo "Running tests..."
  - meson test -C build
  - echo "Creating coverage report..."
  - ninja -C build coverage
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/meson-logs/coverage.xml 
  only:
  - master
  - merge_requests
