image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/hicr/docs:latest

pages:
  tags:
  - docker
  - tiny 
  script:
  - git submodule init && git submodule update
  - tools/check-style.sh check
  - make -C docs
  - mv docs/build/html public
  artifacts:
    paths:
    - public
  only:
  - master
  - merge_requests
