image: alpine

pages:
  tags:
  - docker
  - tiny 
  script:
  - apk update && apk add doxygen graphviz ttf-freefont texlive texmf-dist-latexextra texlive-dvi texlive-font-utils
  - cd docs && doxygen Doxyfile && cd ..
  - mv docs/doxygen/html public
  artifacts:
    paths:
    - public
  only:
  - master
