image: alpine

pages:
  tags:
  - docker
  - tiny 
  script:
  - apk update && apk add doxygen graphviz ttf-freefont texlive texmf-dist-latexextra texlive-dvi
  - pushd docs && doxygen Doxyfile && popd
  - mv docs/doxygen/html public
  artifacts:
    paths:
    - public
  only:
  - master
