#define BLOCK_SIZE 4096 * 4096
#define OBJECT_STORE_TAG 42
#define CHANNEL_PAYLOAD_CAPACITY 1048576
#define CHANNEL_COUNT_CAPACITY 1024
#define CHANNEL_TAG 0xF000
#define SIZES_BUFFER_KEY 0
#define PRODUCER_COORDINATION_BUFFER_FOR_SIZES_KEY 1
#define PRODUCER_COORDINATION_BUFFER_FOR_PAYLOADS_KEY 2
#define CONSUMER_COORDINATION_BUFFER_FOR_SIZES_KEY 3
#define CONSUMER_COORDINATION_BUFFER_FOR_PAYLOADS_KEY 4
#define CONSUMER_PAYLOAD_KEY 5