#pragma once
#include <hicr/backend.hpp>
#include <hicr/channel.hpp>
#include <hicr/common/concurrentQueue.hpp>
#include <hicr/common/coroutine.hpp>
#include <hicr/common/definitions.hpp>
#include <hicr/common/eventMap.hpp>
#include <hicr/common/exceptions.hpp>
#include <hicr/common/logger.hpp>
#include <hicr/dispatcher.hpp>
#include <hicr/processingUnit.hpp>
#include <hicr/task.hpp>
#include <hicr/worker.hpp>
