#pragma once
#include <hicr/backend.hpp>
#include <hicr/backends/sharedMemory/sharedMemory.hpp>
#include <hicr/backends/sharedMemory/thread.hpp>
#include <hicr/channel.hpp>
#include <hicr/common/concurrentQueue.hpp>
#include <hicr/common/coroutine.hpp>
#include <hicr/common/definitions.hpp>
#include <hicr/common/eventMap.hpp>
#include <hicr/common/exceptions.hpp>
#include <hicr/common/logger.hpp>
#include <hicr/computeResource.hpp>
#include <hicr/dataMover.hpp>
#include <hicr/dispatcher.hpp>
#include <hicr/memorySlot.hpp>
#include <hicr/memorySpace.hpp>
#include <hicr/messageTag.hpp>
#include <hicr/runtime.hpp>
#include <hicr/task.hpp>
#include <hicr/worker.hpp>
