#pragma once

#define CHANNEL_TAG 0
#define TOKEN_BUFFER_KEY 0
#define CONSUMER_COORDINATION_BUFFER_KEY 1
#define PRODUCER_COORDINATION_BUFFER_KEY 2
#define MESSAGES_PER_PRODUCER 3
#define ELEMENT_TYPE unsigned int
