#pragma once

#define PAYLOAD_CAPACITY 32
#define CHANNEL_TAG 0
#define PING_BUFFER_KEY 0
#define PONG_BUFFER_KEY 1
#define PRODUCER_PING_COORDINATION_BUFFER_KEY 2
#define PRODUCER_PONG_COORDINATION_BUFFER_KEY 3
#define CONSUMER_PING_COORDINATION_BUFFER_KEY 4
#define CONSUMER_PONG_COORDINATION_BUFFER_KEY 5
#define ELEMENT_TYPE char
