name: Build and Push Docker Images

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: read # this is necessary for the Action to be able to read the contents of the repo

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  check-dockerfile-modifications:
    runs-on: ubuntu-latest
    outputs:
      dockerfile-modified: ${{ steps.check-dockerfile.outputs.dockerfile-modified }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Check the PR diff using the current branch and the base branch of the PR
      - uses: GrantBirki/git-diff-action@v2.8.0
        id: git-diff-action
        with:
          raw_diff_file_output: diff.txt
          file_output_only: "true"
          git_options: "--name-only"

      - name: Check if Dockerfile was modified
        id: check-dockerfile
        env:
          MODIFIED_FILES_PATH: ${{ steps.git-diff-action.outputs.raw-diff-path }}
        run: |
          cat $MODIFIED_FILES_PATH
          if cat $MODIFIED_FILES_PATH | grep -q 'Dockerfile' ; then
            echo "Dockerfile was modified"
            echo "dockerfile-modified=true" >> $GITHUB_OUTPUT
          else
            echo "Dockerfile was not modified"
            echo "dockerfile-modified=false" >> $GITHUB_OUTPUT
          fi


  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [check-dockerfile-modifications]
    if: ${{needs.check-dockerfile-modifications.outputs.dockerfile-modified }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: dockermeta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/buildenv
          tags: latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:.build-tools/containers/buildenv"
          push: true
          tags: ${{ steps.dockermeta.outputs.tags }}
          labels: ${{ steps.dockermeta.outputs.labels }}
        
