name: Build and Push Docker Images

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  check-dockerfile-modifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Check if Dockerfile was modified
        id: check_dockerfile
        run: |
          echo $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q 'Dockerfile'; then
            echo "Dockerfile was modified"
            echo "dockerfile-modified=true" >> $GITHUB_ENV
          else
            echo "Dockerfile was not modified"
            echo "dockerfile-modified=false" >> $GITHUB_ENV
          fi


  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [check-dockerfile-modifications]
    if: ${{ github.env.dockerfile-modified == 'true' }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
  
    steps:
      # If we don't do this docker will fail. Only lowercase images are allowed
      - name: lowercase repository
        run: |
          echo "repository-lowercase=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.env.repository-lowercase }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: dockermeta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/buildenv
          tags: latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # platforms: linux/amd64,linux/arm64
          context: "{{defaultContext}}:.build-tools/containers/buildenv"
          push: true
          tags: ${{ steps.dockermeta.outputs.tags }}
          labels: ${{ steps.dockermeta.outputs.labels }}
        
