name: Build and Run Tests

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  # Build HiCR and run tests
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Updating Apt
      run: sudo apt update
    - name: Installing apt packages
      run: sudo apt install build-essential git libgtest-dev libhwloc-dev openssh-client libopenblas-dev liblapack-dev liblapacke-dev libfabric-dev libibverbs-dev infiniband-diags libboost-context-dev curl jq  python3-pip python3-venv pkgconf wget sudo openssh-client
    - name: Updating submodules 
      run: git submodule update --init --recursive
    - name: 
      run:  |
        echo "Building..."
        mkdir build
        meson setup build -Dbuildtype=debug -Db_coverage=true -Dbackends=hwloc,pthreads,mpi,lpf,nosv,boost,opencl -Dfrontends=channel,RPCEngine,tasking,objectStore -DbuildTests=true -DbuildExamples=true -DcompileWarningsAsErrors=true
        meson compile -C build
        echo "Running tests..."
        meson test -C build
        echo "Creating coverage report..."
        ninja -C build coverage
