name: Build and Run Tests

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  # Build HiCR and run tests
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Updating Apt
      run: sudo apt update
    - name: Installing apt packages
      run: sudo apt install clang-format doxygen graphviz
    - name: Updating submodules 
      run: git submodule update --init --recursive
    - name: 
      run:  |
        export HOME=/home/hicr
        source /home/hicr/.hicr-env.sh
        echo "Building..."
        mkdir build
        meson setup build -Dbuildtype=debug -Db_coverage=true -Dbackends=hwloc,pthreads,mpi,lpf,nosv,boost,opencl -Dfrontends=channel,RPCEngine,tasking,objectStore -DbuildTests=true -DbuildExamples=true -DcompileWarningsAsErrors=true
        meson compile -C build
        echo "Running tests..."
        meson test -C build
        echo "Creating coverage report..."
        ninja -C build coverage
